### ISSUE TITLE
Place markers do not overlap properly

### ISSUE THREAD

**Issue by arkin0x** [innovatario/yondar-mono#1]
It would seem more correct for the place markers to be a lower z-index (farther from the viewer) as they got closer to the north or south pole, as the Earth is normally viewed from the equator.

To change the z-order of the markers, I have only found the `key` property of the `<Marker ...>` to be effective at influencing the sort, which appears to be standard alpha sort. Right now the `key` is the place id (event id). This is useful because it prevents React from re-rendering the `<Marker ...>`s many times which causes ugly content flickers.  However, the problem is that the beacons are not sorted properly by latitude and rather are sorted quite randomly by event id.

The solution may be to use a <Source> with beacon coords and a <Layer> to display a flat beacon indicator, and only have a marker pop up under a certain condition, because already there are enough markers to cause log in the render loop.

Possible solution: 
- make markers only appear at a certain close zoom threshold; before that, the places are only represented by some small indicator rendered by a `<Source><Layer/></Source>`

**Comment by samuelralak** [comment]
@arkin0x claiming this issue

**Comment by arkin0x** [comment]
> @arkin0x claiming this issue

Hello @samuelralak 

This issue has been moved to https://nostrocket.org/problems/cac4201361474480fb26884a0c8e196c7d1f58775a6c91c2537971ba143a00a1

I believe you are in the identity tree already but please ping me if you have any problems
