### ISSUE TITLE
Add location/business ratings scale

### ISSUE THREAD

**Issue by alltheseas** [innovatario/yondar-mono#10]
## Required reading

https://habla.news/u/arkinox@arkinox.tech/DLAfzJJpQDS4vj3wSleum

## User Story

As a Yondar map explorer, I would like a way to see how Yondar-erers rate a particular location, so that I can become more informed about a particular location.

### Acceptance Criteria

1. There is a clear method to see location ratings on a selected Yondar location

### How Might We Design

Suggested scale: add a three tier scale for rating a location/business. 

~~Positive: 😀~~ Positive 👍
~~Neutral : 😐~~ Mixed Reviews 🤨
~~Negative: 😞~~ Negative 👎

### Mockup

<img width="327" alt="Screenshot 2023-11-13 at 10 29 24 AM" src="https://github.com/innovatario/yondar-mono/assets/64376233/bdfdd549-c29b-44d1-816b-24a485e8fcf6">

_Future_

Over time can expand to multiple categories/metrics. See example below.

![image](https://github.com/innovatario/yondar-mono/assets/64376233/21dc8293-f065-4ba0-acf7-0f7f52be3459)

**Comment by arkin0x** [comment]
I have been thinking a lot about ratings and wrote a whole article about how to do them better with NIP-32:

https://habla.news/u/arkinox@arkinox.tech/DLAfzJJpQDS4vj3wSleum

I want to implement QTS for Yondar! Feedback on QTS would be appreciated!

**Comment by alltheseas** [comment]
> this would result in a rating between 0 "bad" and 0.5 "good".

I suppose the range does not matter, as long as the reviewer has simply two options: thumbs-up 👍 , and thumbs-down 👎.

>  QTS balances this with a "bad" rating at 0, a "good" rating at 0.5, and an excellent rating is anything above 0.5 (up to 1.0)

I am not sure I understand why 1.0 is referenced, when previously the range was defined as 0 to 0.5. 

 > A score is derived as follows:
a thumbs-down is a score of 0.00
a thumbs-up is a score of 0.50
a label is worth 0.50 ÷ the number of labels available. So, if there are 3 labels to pick from, each label is worth 0.1666. The labels should all have the same value.

This seems agreeable. I suggest that if it helps build towards a MVP quicker, the simplest way to get started is not to have labels. This can be added as an increment.

**Comment by arkin0x** [comment]
Moved to https://nostrocket.org/problems/db0998c94bff2e138b919c143d39d9c2f893be30bc481666019d043afdfd057a
