### ISSUE TITLE
Add ability to manually add ratings

### ISSUE THREAD

**Issue by alltheseas** [innovatario/yondar-mono#11]
### Builds on

Add ratings scale https://github.com/innovatario/yondar-mono/issues/10

## User Story

As a Yondar-er who has knowledge about a location, I would like to be able to add a rating for said location, so that I can provide value for other Yondar-ers, which in turn I expect to increase the value of Yondar to me.

### Acceptance criteria

1. The user wanting to leave a review has an easy way to provide a rating while browsing Yondar

### How might we, design, and implementation

How might we parse reviews from regular notes/kind1s that evaluate a business outside of Yondar?
LLMs, and data vending machines?

**Comment by arkin0x** [comment]
I've split this: the first part is merged into #10 and the second part about parsing reviews has been moved to https://nostrocket.org/problems/ff7fe2b30974b7da9d876512ce709510cd22b154f3ad452ff10c8e0196e1263b
