### ISSUE TITLE
Add NIP-05 Support

### ISSUE THREAD

**Issue by arkin0x** [innovatario/yondar-mono#2]
- [ ] show NIP-05 in geochat
- [ ] show NIP-05 on place details

**Comment by shoupn** [comment]
Is it cool if I pick this up?

**Comment by arkin0x** [comment]
@shoupn Absolutely!

**Comment by shoupn** [comment]
Awesome! I'll reach out on TG if I have any questions.

**Comment by arkin0x** [comment]
@shoupn I've moved this problem to https://nostrocket.org/problems/9b94d58ff06562199b967f65ab296b43294b9f72bf72517806a34fbdfd606a88
