### ISSUE TITLE
Add dialogue box beneath the location box

### ISSUE THREAD

**Issue by alltheseas** [innovatario/yondar-mono#3]
_experimental suggestion_
If every location box is a nostr note or event, why not experiment with adding a thread for each event underneath the geo box?

_mockup_

<img width="701" alt="Screenshot 2023-11-07 at 9 53 18 PM" src="https://github.com/innovatario/yondar-mono/assets/64376233/e5a3f375-3d87-4485-bf3a-5853dc3c9e53">

**Comment by arkin0x** [comment]
Yes, thank you for the mockup. We will be adding comments and reviews that appear in a similar fashion to this! 🤙

**Comment by arkin0x** [comment]
Moved to https://nostrocket.org/problems/db0998c94bff2e138b919c143d39d9c2f893be30bc481666019d043afdfd057a
