### ISSUE TITLE
Problem: Missing contribution guideline

### ISSUE THREAD

**Issue by samuelralak** [innovatario/yondar-mono#4]
Problem:
Currently, the repository lacks contribution guidelines. This omission can lead to potential contributors being unsure about how to proceed with contributions, which can result in inconsistent code submissions, improperly formatted pull requests, or even deter contributors from participating in the development process altogether.

Solution:
I propose the addition of a README.md and/or CONTRIBUTING.md  file to the repository. This document should outline the necessary steps for setting up the development environment, the process for submitting pull requests, coding standards, and how to report bugs or suggest features. Providing a clear set of instructions will help in streamlining contributions, maintaining code quality, and making the process of contributing clear and accessible to newcomers.

**Comment by arkin0x** [comment]
Greetings Samuel. I think this is a good idea. I have never created contributing guidelines before but I can take a shot at it. Suggestions welcome.

**Comment by weex** [comment]
I'd suggest using C4. This is from libzmq and can be tacked on the end of the readme:

# Contributing
This project uses [C4(Collective Code Construction Contract)](https://rfc.zeromq.org/spec:42/C4/) process for contributions.

**Comment by samuelralak** [comment]
@weex I am  in full support; however some discussion will be needed around changing the license from CC to MPLv2, or a GPLv3 (as stated in the C4) 🤔

cc: @arkin0x

**Comment by arkin0x** [comment]
I can modify the C4 to work with the existing license that we have applied to this repository: https://github.com/innovatario/yondar-mono/blob/master/LICENSE

**Comment by arkin0x** [comment]
@samuelralak @weex Hello! I have been informed that Nostrocket defines the contribution guideline for all projects under it, so this will be taken care of automatically.
