### ISSUE TITLE
Improve interoperability of Yondar on other nostr clients: Image preview of map + title text displayed on image on nostr clients

### ISSUE THREAD

**Issue by alltheseas** [innovatario/yondar-mono#8]
_what happens currently_

When sharing on nostr and opening with Iris/Snort, and Damus, result is a gibberish link with little context. 

<img width="709" alt="Screenshot 2023-11-10 at 10 01 52 PM" src="https://github.com/innovatario/yondar-mono/assets/64376233/a5c44dbb-1e02-4414-89e7-6b567e4d71bf">

![image](https://github.com/innovatario/yondar-mono/assets/64376233/95091fd4-fbbc-4de3-919e-85f2a8187706)

_what I think should happen_
There should be a preview with:
1) a static image of the location of interest
2) title text displayed on said image of location

Static screenshot of yondar below without modificaitons. 
<img width="870" alt="Screenshot 2023-11-10 at 10 06 53 PM" src="https://github.com/innovatario/yondar-mono/assets/64376233/325ec314-0a80-49f0-8432-eb6c796d6697">

### Mockup
![Preview Map on Nostr Post](https://github.com/innovatario/yondar-mono/assets/64376233/6741fc8c-fbd5-494c-ad88-89382510f03f)

**Comment by alltheseas** [comment]
Added mockup

**Comment by arkin0x** [comment]
Thanks for the mockup @alltheseas ! I completely agree with this.

In order to provide place-specific previews, we need to have the server generate a preview image based on the naddr and then update the open graph meta tags to reference that image before the response is sent. I've never implemented something like this before so, help wanted!

**Comment by alltheseas** [comment]
> Thanks for the mockup @alltheseas ! I completely agree with this.
> 
> In order to provide place-specific previews, we need to have the server generate a preview image based on the naddr and then update the open graph meta tags to reference that image before the response is sent. I've never implemented something like this before so, help wanted!

@arkin0x this is the how @fiatjaf implemented njump, which I see as an analogue & potential example https://github.com/fiatjaf/njump

**Comment by arkin0x** [comment]
Moved to https://nostrocket.org/problems/d892f139ebed930c31dd02ef433e8eb305e7583a3008327b17809a50fa05e697

**Comment by alltheseas** [comment]
@arkin0x can you add my desktop npub to the issue I created 🙏  npub170daa0erwfccerqgzng8n08rt8rcqn5w2xme7p9glcgplwdmv4uqr6szps

**Comment by arkin0x** [comment]
> @arkin0x can you add my desktop npub below to the issue I created 🙏 on nostrocket npub170daa0erwfccerqgzng8n08rt8rcqn5w2xme7p9glcgplwdmv4uqr6szps

Done!
