### ISSUE TITLE
Add number of times a location has been mentioned (design help needed 🛟)

### ISSUE THREAD

**Issue by alltheseas** [innovatario/yondar-mono#9]
## user story

As a Yondar map explorer, I would like to see how many times a particular business/location has been mentioned, so that I have an idea of "trending" businesses/locations on nostr.

### acceptance criteria
1. Display visually on Yondar location pin how many times said location/business has been mentioned

### Mockup

![image](https://github.com/innovatario/yondar-mono/assets/64376233/2a3e960e-2388-401e-aba2-8141ea9c09d4)

**Comment by arkin0x** [comment]
I moved and aggregated some of your issues here @alltheseas : https://nostrocket.org/problems/f48205a6ec8a73eef4eb683d01e56a6731b11fbedd61e244380704ad9345350f
